### ISSUE TITLE
Docker compose is broken 

### ISSUE THREAD

**Issue by bertonjulian** [seek-oss/listo#32]
Attaching to listo_listo_1
listo_1  | internal/modules/cjs/loader.js:638
listo_1  |     throw err;
listo_1  |     ^
listo_1  |
listo_1  | Error: Cannot find module '../../frontend/src/types'
listo_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
listo_1  |     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
listo_1  |     at Module.require (internal/modules/cjs/loader.js:692:17)
listo_1  |     at require (internal/modules/cjs/helpers.js:25:18)
listo_1  |     at Object.<anonymous> (/opt/listo/server/diskdb.js:6:17)
listo_1  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
listo_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
listo_1  |     at Module.load (internal/modules/cjs/loader.js:653:32)
listo_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
listo_1  |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
listo_listo_1 exited with code 1

**Comment by bertonjulian** [comment]
#34
